### ISSUE TITLE
What is 'default_button_01' ?

### ISSUE THREAD

**Issue by BlushTTV** [almighty059/acinfinityhomeassistantcard#1]
![image](https://github.com/almighty059/acinfinityhomeassistantcard/assets/54521936/d82a8f66-b60a-4c93-b637-18001af82ed4)

**Comment by almighty059** [comment]
I think I added it now to the button template. I use it that as a starting point for all my button cards throughout my entire dashboard.

```
  default_button_01:
    show_icon: false
    styles:
      card:
        - height: 100%
        - '--mdc-ripple-color': white
        - '--mdc-ripple-press-opacity': 0.5
        - border-radius: 10%
        - padding: 5%
        - border-color: rgba(119, 119, 119, 0.4)
        - box-shadow: 0px 0px 0px 0px var(--primary-text-color)
      name:
        - font-size: 20px
        - font-weight: none
    tap_action: []
    double_tap_action: []
    hold_action: []
```

**Comment by almighty059** [comment]
You'll probably have to change a lot of the styling so that it loves right with your dashboard. Let me know which part you get hung up on and I'll try and help you out.

**Comment by maziggy** [comment]
I'm having troubles including the button_card_templates. Can you please assist? Thx!

<img width="921" alt="Screenshot 2024-09-30 at 10 15 28" src="https://github.com/user-attachments/assets/336c46ce-44ba-48a9-87fc-6c1a138310f3">

# configuration.yaml
`template: !include templates.yaml
`
# templates.yaml
`button_card_templates:
  default_button_01:
    show_icon: false
    styles:
      card:
        - height: 100%
        - '--mdc-ripple-color': white
        - '--mdc-ripple-press-opacity': 0.5
        - border-radius: 10%
        - padding: 5%
        - border-color: rgba(119, 119, 119, 0.4)
        - box-shadow: 0px 0px 0px 0px var(--primary-text-color)
      name:
        - font-size: 20px
        - font-weight: none
    tap_action: []
    double_tap_action: []
    hold_action: []
  ac_infinity_button_mode_state_01:
    show_icon: false
    tap_action:
      action: call-service
      service: select.select_option
      service_data:
        option: '[[[ return variables.var_selected_mode ]]]'
        entity_id: '[[[ return entity.entity_id ]]]'
    double_tap_action: []
    hold_action: []
    styles:
      card:
        - height: 100%
        - '--mdc-ripple-color': white
        - '--mdc-ripple-press-opacity': 0.5
        - border-radius: 10%
        - padding: 5%
        - box-shadow: 0px 0px 0px 0px var(--primary-text-color)
        - background-color: |
            [[[
              if (entity.state == variables.var_selected_mode)
                return 'rgba(255, 255, 255, 0.1 )';
              else return '';
            ]]]
      name:
        - font-size: 12px
        - color: |
            [[[
              if (entity.state == variables.var_selected_mode)
                return 'rgba(255, 255, 255, 1.0 )';
              else return 'var(--disabled-text-color)';
            ]]]
        - font-weight: |
            [[[
              if (entity.state == variables.var_selected_mode)
                return 500;
              else return '';
            ]]]
  ac_infinity_port_state_01:
    show_name: true
    show_icon: false
    show_state: true
    tap_action: []
    double_tap_action: []
    hold_action: []
    styles:
      name:
        - font-size: 14px
      state:
        - font-size: 14px
        - color: |
            [[[
              if (entity.state == 'On')
                return 'rgba(255, 255, 255, 1.0 )';
              else return 'var(--disabled-text-color)';
            ]]]
      card:
        - height: 100%
        - border-radius: 10%
        - padding: 5%
        - box-shadow: 0px 0px 0px 0px var(--primary-text-color)
        - background-color: |
            [[[
              if (entity.state == 'On')
                return 'rgba(255, 255, 255, 0.3 )';
              else if (entity.state == 'Off')
                return 'rgba(255, 255, 255, 0.1 )';
              else return 'rgba(255, 0, 0, 0.1 )';
            ]]]
      label:
        - font-size: 12px
      grid:
        - grid-template-areas: '"n" "l" "s"'
        - grid-template-columns: 1fr
        - grid-template-rows: auto`

**Comment by almighty059** [comment]
> I'm having troubles including the button_card_templates. Can you please assist? Thx!

When I originally began using button templates I tried what you did but used `button_templates` and could not get it to work. With that being said, you're using `template` which is for sensor templates and not button templates. As far as I know, button templates must be added to your dashboard yaml by using the Raw Configuration Editor and entering them above everything else. Be careful when using the Editor because it contains the raw yaml for your entire dashboard.


<img src="https://github.com/user-attachments/assets/64896e6f-7990-4434-aa87-fa3e9cd146d5" width="50%" height="50%">


I use `default_button_01` throughout my entire dashboard as a standard template so I don't have to repeat the same code for each button. I do the same with other buttons. You can either delete the use of the template and add what you want from the template to the actual button card or you add my template and if you need to modify it to work with your dashboard. 


```
button_card_templates:
  default_button_01:
    aspect_ratio: 1/1
    show_icon: false
    styles:
      card:
        - '--mdc-ripple-color': white
        - '--mdc-ripple-press-opacity': 0.5
        - border-radius: 10%
        - padding: 5%
        - border-color: rgba(119, 119, 119, 0.4)
        - box-shadow: 0px 0px 0px 0px var(--primary-text-color)
      name:
        - font-size: 20px
        - font-weight: none
    tap_action: []
    double_tap_action: []
    hold_action: []
  additional_example_template_01:
    aspect_ratio: 1/1
    show_icon: false
  additional_example_template_02:
    aspect_ratio: 1/1
    show_icon: false

# Additional templates can be added like the examples above.
# Make sure they are above the below `views:` portion of your dashboard yaml.

views:
  - theme: My Dark Theme
    title: Rooms
    path: rooms
    icon: mdi:lamps-outline
```
